version: "3.6"
services:
    app:
        build: .
        ports:
            - 5000:5000
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    db-data:
networks:
    default:
        name: ict_net
        external: true
