version: "3.6"
services:
    app:
        build: .
        ports:
            - 5001:5001
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mysecretpassword
            POSTGRES_DB: postgres
        ports:
            - 5433:5432
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
networks:
    default:
        name: ict_net
        external: true
